name: pre-commit

on:
  push:
    branches: [main] # Déclenche l'action uniquement sur la branche main (ou ajustez si nécessaire)

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8' # Spécifiez la version de Python dont vous avez besoin
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Install dependances
      run: pip install -r requirements.txt
    - name: Install hooks
      run: pre-commit install
    - name: Run pre-commit hooks
      run: pre-commit run --all-files
